### PR TITLE
New Google Sheet for data, script to update data files from that

### PR DESCRIPTION
**Pull request by abesto**
I've spent some time creating a new Google Sheet that contains only and exactly the data used by this app, and some tooling to update the data in the app with one command. This should hopefully
* provide a bit of extra transparency, maybe enable collaboration (the sheet is publicly readable, but of course not writable)
* make it easier to work with the data
  * I added a few additional pieces of data verification right to the spreadsheet
  * The Tracks sheet in particular should be much nicer to work with now - thanks to the Data Verification feature of Google Docs, we now have checkboxes there
  * it's now completely clear what pieces are used by the app; namely: exactly what's in this new sheet
* eliminate human error in the Google Sheet -> app import step

@rsr427 I'd appreciate your eyes on, and thoughts about
* The sheet at https://docs.google.com/spreadsheets/d/1v4awipFv6t0RVoDaFyY8n5JgqQFdUKeXmKZN_hwTu0Q/edit#gid=0 (you have edit rights)
* The changes to the `.csv` files below. Expected changes:
  * Added a few car manufacturing years {as seen in #43)
  * Fixed some `headlights` values (they were incorrectly aggregated before from cars to car class)
  * Dropped the `grade` field from `cars.csv` as it's not used (the grade number _actually_ used is in `car_classes.csv`)
  * Applied an extra bit of sorting to the cars sheet (so you'll see a few cars swapping places in the order in `cars.csv`)

I've published a preview version of the app using these new changes to https://d4sk2ytizwr62.cloudfront.net/ (same caveats as before: going directly to https://d4sk2ytizwr62.cloudfront.net/career won't work, but clicking through the menu from https://d4sk2ytizwr62.cloudfront.net/ _will_).

### CODE REVIEW

**Comment by rsr427** [comment]
Files look clean.  I updated the Track matrix with the new tracks both in this file and the old file.  The old file could tell me how many classes would race at that track, which is helpful.  It was copy and paste otherwise.

I used a video from RD to get the configuration names since I don't have AMS2 with me currently.  I thought there were supposed to be multiple Cordoba configurations, but apparently we have one for now.  I will update as more are released.

**Comment by abesto** [comment]
Lovely, thank you!

> The old file could tell me how many classes would race at that track, which is helpful.
If that's good enough for you, a new tab in the new sheet would be a safe way to do this - another tab won't confuse the automation.

> I updated the Track matrix with the new tracks both in this file and the old file.
Nice, I'll pull those in, time to see the automation in action! :D

> I used a video from RD to get the configuration names since I don't have AMS2 with me currently.
Hah, I'll double-check then just in case.

**Comment by rsr427** [comment]
Differences I see between the sheet and the sim:

Buenos Aires has a "No.6 S" layout that's currently missing from the sheet. Shall I add it in, with the same classes as the No.6 layout? (or leave it to you)

Definitely include it. I'm not sure what the layout is and that usually drove what series raced there. If it's a smaller track, I usually only include National type series, whereas larger layouts are for more international series. If the layout difference is a chicane, it could probably be the same.

The Buenos Aires layouts in-game don't seem to have the human-friendly names in parentheses, like (Modern). Shall we drop them to avoid confusion? Or keep them in for extra information? Where do they even come from?

They come from my little brain and what I know about the tracks history. I thought they might help the user pick the right track in-game, but the names of the layouts are probably clear enough. It was probably more helpful to me than for other people.

The circuit name for Buenos Aires seems to be "Buenos Aires Circuito". I'd probably opt for using that full name.

Use the full name, for sure.

Note that the default "Group By Location" in-game actually groups by location / city. Most of the time the city is a prefix of the name of the circuit, but not always. For example under Granja Viana we have both "Copa Sao Paulo Kart Stage 2" (note the complete lack of "Granja Viana" in the track name) and Granja Viana Kart 101. Unfortunately this means the current Track / Configuration setup we have is basically broken; my best idea is to transition to a Location / Configuration setup. By "broken" I mean that from "Copa Sao Paulo Kart Stage 2" there's no way in the game to find out that it's hidden under "Granja Viana". A problem for another day - just filed #59 for this.

I'll keep an eye out for a resolution. Fingered crossed for an API solution...

Cordoba does have additional layouts: No.2 and No.4. Shall I add them with the same classes as the TC layout? (or leave it to you)

This goes back to my National vs International layout ideology. I would honestly want to study what the layouts are used for. My bet is that the main layout is probably equivalent to the type of track that the Brazil Stock car series races in. For the smaller layouts, probably like the tracks I picked for the Club racing series. Does that make sense? But I can come back with a definitive answer.

Córdoba in-game has an accent on the first "o". By default I'd say let's include it (the app should be just fine, in theory, but I'll test). Do you actively think we should leave accents out instead? (Same for Termas de Río Hondo)

Dude, I don't know how to do the accents. But yes, I think that should be the case.

Sorry I can't highlight my responses neatly, I can't figure it out on this mail app...

⁣Get BlueMail for Android ​

**Comment by abesto** [comment]
>Buenos Aires No.6 S [...] If the layout difference is a chicane, it could probably be the same.

Yep, it's a chicane. Added to the sheet with the same classes as No.6!

Buenos Aires track / layout names: alright, I've just removed the human-friendly names in parentheses to match the game, and added the full name. While I was at it, I dropped the space between "No." and the number to completely match the in-game name (so "No.6", instead of "No. 6").

> This goes back to my National vs International layout ideology. I would honestly want to study what the layouts are used for. My bet is that the main layout is probably equivalent to the type of track that the Brazil Stock car series races in. For the smaller layouts, probably like the tracks I picked for the Club racing series. Does that make sense? But I can come back with a definitive answer.

Yep, makes perfect sense! No.2 is a short layout, No.4 is the same as TC, just has ~2 extra turns (longer than a chicane). Would love if you could add these, make sure the classes make sense / are consistent with the other stuff we have.

> Dude, I don't know how to do the accents. But yes, I think that should be the case.

Lol, ok :D My secret trick is plopping the name of the track into Google / Wikipedia, then copy-pasting from there :P Gave this a bit of thought, turns out it's a bit more involved than I initially thought: https://github.com/abesto/ams2-career/issues/60. For the moment, let's *not* add accents; I'll tackle this separately.

> Sorry I can't highlight my responses neatly, I can't figure it out on this mail app...

Heh, no worries, it's pretty clear as is. FWIW, I'd expect emails to support [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as well, but have never actually tested this (so a quote would be: start the line with a `>` character)

**Comment by rsr427** [comment]
We can use a simplistic assumption for the Buenos Aires for now. I'll work on a more accurate distribution across classes.

Another value-add we provide for the AMS2 community.

Thanks, Ryan

⁣Get BlueMail for Android ​

**Pull request merged**
